<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>block_racing_server</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Core\" />
    <Folder Include="Database\" />
    <Folder Include="Game\Fields\" />
    <Folder Include="Game\Blocks\" />
    <Folder Include="Game\Collisions\" />
    <Folder Include="Game\Tick\" />
  </ItemGroup>

</Project>
